# Generated by Django 6.1.1 on 2026-09-13 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_facil', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('foto', models.ImageField(upload_to='reportes/fotos/')),
                ('documento', models.FileField(blank=True, upload_to='reportes/documentos')),
                ('audio', models.FileField(blank=True, upload_to='reportes/audios/')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('video', models.FileField(blank=True, upload_to='reportes/videos')),
            ],
        ),
    ]
